version: '3.2'

services:
  lbhtenancyapi:
    image: lbhtenancyapi
    build:
      context: .
      dockerfile: LBHTenancyAPI/Dockerfile
      args:
        - VERSION_SUFFIX 
    ports:
      - 3000:80
    links:
     - stubuniversalhousing
  lbhtenancyapitest:
    image: lbhtenancyapitest
    build:
      context: .
      dockerfile: LBHTenancyAPITest/Dockerfile
    links:
     - lbhtenancyapi
     - stubuniversalhousing
  stubuniversalhousing:
    image: stubuniversalhousing
    build:
      context: .
      dockerfile: StubUniversalHousing/Dockerfile
    ports:
      - 1433:1433

